version: '3.3'

services:
  db:
    image: postgres:15.6
    environment:
      POSTGRES_DB: challenge_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: '12345'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: test_user
      DB_PASS: '12345'
      DB_NAME: challenge_db
    entrypoint: /bin/bash -c "bundle exec rake db:create && bundle exec rake db:migrate && bundle exec rake features:fetch && bundle exec rails s -b '0.0.0.0'"
